version: "3.0"

services:

   db:
       image: postgres:14.2
       container_name: postgres-TTB
       command: --default-authentication-plugin=mysql_native_password
       restart: always
       ports:
         - "8080:8080"
       environment:
        - POSTGRES_USER=chloe
        - POSTGRES_PASSWORD=mdp

   backend:
       image: ttbback
       container_name: ttb-backend
       restart: always
       build:
         context: ./backend
         dockerfile: Dockerfile
       ports:
         - "8080:8080"
       depends_on:
         - db
       environment:
          - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ttb
          - SPRING_DATASOURCE_USERNAME=chloe
          - SPRING_DATASOURCE_PASSWORD=mdp
          - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
       networks: # Networks to join (Services on the same network can communicate with each other using their name)
         - backend